### ISSUE TITLE
Nuget packages for reference implementations

### ISSUE THREAD

**Issue by JoshCollinsMSFT** [Microsoft/CorrelationVector#4]
Is there a plan to create nuget packages for the reference implementations?

While the code is very light weight and relatively easy to integrate into a solution, I would prefer to just reference a package.

**Comment by jacpull** [comment]
Yes, this is the plan. We do have several nuget packages which includes the reference implementations including automatic propagation. But these are not open sourced at the moment. We will get an ETA out for a OSS implementation next week. Can you specify if you have a language preference for prioritization.

**Comment by JoshCollinsMSFT** [comment]
We write everything in C# right now, so that would be our preference.

**Comment by jacpull** [comment]
Attn: @brian-pm

**Comment by mohit1234** [comment]
We plan to get the C# nuget package out by the end of next week (Dec 14th).

**Comment by CameronGoodwin** [comment]
Groovy.

**Comment by mohit1234** [comment]
The C# Nuget package is now available on [nuget.org](https://www.nuget.org/packages/Microsoft.CorrelationVector/)
